### ISSUE TITLE
Help! The parts list is too hard to read 😱😱😱😱😱😱😱

### ISSUE THREAD

**Issue by sspaeth-r7** [pineapplee0/Flight-Doorbell#5]
# 😱😱😱😱😱😱😱😱
Please help the parts list i can't read it!!!!!!11!!!!!!!!!

Here's a suggestion: https://www.markdownguide.org/extended-syntax/#tables

🙂 

Thanks. Pineapple.

**Comment by pineapplee0** [comment]
Hello dearest fan, I have fixed the issue. There will be none in the future. 😀
